language: rust
sudo: required
email:
  recipients:
    - trishume@gmail.com
  on_success: change # default: change
  on_failure: change # default: always

matrix:
  include:
    - rust: stable
      addons:
        apt:
          packages:
            # cargo-tarpaulin needs this
            - libssl-dev
    - rust: beta
    - rust: nightly
  allow_failures:
    - rust: nightly

cache:
  - apt
  - cargo

script:
  - cargo build
  - |
    if [ "$TRAVIS_OS_NAME" == "linux" ]
    then
      p=$(cd ./target/debug/build/onig_sys-*/out/lib/ && pwd)
      echo "adding $p to linker path"
      export LD_LIBRARY_PATH="${p}:${LD_LIBRARY_PATH}"
    fi
  - cargo test
  - make assets
  - rm -Rf examples
  - cargo doc
  # default features are required for examples to build - so remove them from sight.
  # Doc-tests may also use default features
  - rm -Rf examples && cargo test --lib --no-default-features
  # Test the build configuration that Xi uses
  - cargo test --lib --no-default-features --features "assets dump-load-rs"

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" = stable ]]; then
    bash <(curl https://raw.githubusercontent.com/xd009642/tarpaulin/master/travis-install.sh)
    # Calculate test coverage
    cargo tarpaulin --out Xml
    bash <(curl -s https://codecov.io/bash)
  fi
